export type ComponentCategory =
  | '基础与内容'
  | '表单与选择'
  | '导航与结构'
  | '覆盖层与菜单'
  | '数据与反馈'
  | '消息与会话'

export type ComponentDoc = {
  id: string
  name: string
  title: string
  category: ComponentCategory
  description: string
  composition: string[]
  states: string[]
}

export const categories: ComponentCategory[] = [
  '基础与内容',
  '表单与选择',
  '导航与结构',
  '覆盖层与菜单',
  '数据与反馈',
  '消息与会话',
]

export const componentDocs: ComponentDoc[] = [
  {
    id: 'accordion',
    name: 'Accordion',
    title: '手风琴',
    category: '基础与内容',
    description: '在有限空间内按主题展开或收起内容，适合 FAQ、设置分组和渐进披露。',
    composition: ['Accordion', '├─ AccordionItem', '│  ├─ AccordionTrigger', '│  └─ AccordionContent'],
    states: ['收起', '展开', '禁用'],
  },
  {
    id: 'alert',
    name: 'Alert',
    title: '提示',
    category: '数据与反馈',
    description: '用于呈现需要被注意但不一定阻断流程的状态、说明或错误信息。',
    composition: ['Alert', '├─ AlertTitle', '├─ AlertDescription', '└─ AlertAction'],
    states: ['默认', '破坏性', '带操作'],
  },
  {
    id: 'alert-dialog',
    name: 'Alert Dialog',
    title: '确认对话框',
    category: '覆盖层与菜单',
    description: '在高风险或不可逆操作前要求用户明确确认，强调后果与恢复路径。',
    composition: ['AlertDialog', '├─ AlertDialogTrigger', '└─ AlertDialogContent', '   ├─ AlertDialogHeader', '   ├─ AlertDialogFooter', '   ├─ AlertDialogCancel', '   └─ AlertDialogAction'],
    states: ['关闭', '打开', '取消', '确认'],
  },
  {
    id: 'aspect-ratio',
    name: 'Aspect Ratio',
    title: '宽高比容器',
    category: '基础与内容',
    description: '让媒体或占位内容保持稳定比例，避免布局跳动。',
    composition: ['AspectRatio', '└─ content'],
    states: ['16:9', '4:3', '1:1'],
  },
  {
    id: 'attachment',
    name: 'Attachment',
    title: '附件',
    category: '消息与会话',
    description: '展示上传或处理中的文件、图片与操作，状态应持续可见。',
    composition: ['Attachment', '├─ AttachmentMedia', '├─ AttachmentContent', '│  ├─ AttachmentTitle', '│  └─ AttachmentDescription', '└─ AttachmentActions'],
    states: ['待上传', '上传中', '处理中', '失败', '完成', '横向', '纵向'],
  },
  {
    id: 'avatar',
    name: 'Avatar',
    title: '头像',
    category: '基础与内容',
    description: '以图片或回退内容表示用户、组织或实体身份。',
    composition: ['Avatar', '├─ AvatarImage', '└─ AvatarFallback'],
    states: ['图片', '回退', '不同尺寸'],
  },
  {
    id: 'badge',
    name: 'Badge',
    title: '徽标',
    category: '基础与内容',
    description: '用紧凑标签表达分类、状态或轻量强调，不替代正文信息。',
    composition: ['Badge', '└─ label / icon'],
    states: ['默认', '次级', '轮廓', '破坏性'],
  },
  {
    id: 'breadcrumb',
    name: 'Breadcrumb',
    title: '面包屑',
    category: '导航与结构',
    description: '表达当前位置在层级结构中的路径，并提供回到上级的路径。',
    composition: ['Breadcrumb', '└─ BreadcrumbList', '   ├─ BreadcrumbItem', '   │  ├─ BreadcrumbLink', '   │  └─ BreadcrumbPage', '   ├─ BreadcrumbSeparator', '   └─ BreadcrumbEllipsis'],
    states: ['链接', '当前页', '省略'],
  },
  {
    id: 'bubble',
    name: 'Bubble',
    title: '消息气泡',
    category: '消息与会话',
    description: '呈现一段对话内容，可通过对齐和表面区分不同发送方。',
    composition: ['BubbleGroup', '└─ Bubble', '   ├─ BubbleContent', '   └─ BubbleReactions'],
    states: ['默认', '次级', '弱化', '着色', '轮廓', '幽灵', '破坏性', '左对齐', '右对齐'],
  },
  {
    id: 'button',
    name: 'Button',
    title: '按钮',
    category: '基础与内容',
    description: '触发动作或状态变化。按钮的动作语义、视觉层级与瞬时反馈必须保持一致。',
    composition: ['Button', '└─ label / icon'],
    states: ['默认', '悬停', '按下', '焦点', '禁用', '默认样式', '次级', '轮廓', '幽灵', '破坏性', '链接', 'XS / SM / MD / LG'],
  },
  {
    id: 'button-group',
    name: 'Button Group',
    title: '按钮组',
    category: '基础与内容',
    description: '将语义相关的按钮组织为连续控制组，适合分段操作和组合动作。',
    composition: ['ButtonGroup', '├─ Button', '├─ ButtonGroupSeparator', '└─ ButtonGroupText'],
    states: ['水平', '垂直', '分隔', '禁用项'],
  },
  {
    id: 'calendar',
    name: 'Calendar',
    title: '日历',
    category: '表单与选择',
    description: '在日期网格中浏览和选择日期，应明确今天、选中、不可用与范围关系。',
    composition: ['Calendar', '├─ CalendarHeader', '├─ CalendarGrid', '└─ CalendarCell'],
    states: ['今天', '默认日期', '选中', '禁用', '范围起点 / 中间 / 终点'],
  },
  {
    id: 'card',
    name: 'Card',
    title: '卡片',
    category: '基础与内容',
    description: '组织一个有明确内部关系的内容单元，不应用于把所有内容都容器化。',
    composition: ['Card', '├─ CardHeader', '│  ├─ CardTitle', '│  ├─ CardDescription', '│  └─ CardAction', '├─ CardContent', '└─ CardFooter'],
    states: ['默认', '小尺寸', '带操作', '带页脚'],
  },
  {
    id: 'carousel',
    name: 'Carousel',
    title: '轮播',
    category: '导航与结构',
    description: '在同一视窗中浏览一组同级内容，前后操作应体现边界状态。',
    composition: ['Carousel', '├─ CarouselContent', '│  └─ CarouselItem', '├─ CarouselPrevious', '└─ CarouselNext'],
    states: ['首项', '中间', '末项', '上一页禁用', '下一页禁用'],
  },
  {
    id: 'chart',
    name: 'Chart',
    title: '图表容器',
    category: '数据与反馈',
    description: '为图表建立一致的颜色、Tooltip、Legend 与响应式容器语法。',
    composition: ['ChartContainer', '├─ chart primitive', '├─ ChartTooltip / ChartTooltipContent', '└─ ChartLegend / ChartLegendContent'],
    states: ['静态数据', '悬停提示', '图例', '空数据'],
  },
  {
    id: 'checkbox',
    name: 'Checkbox',
    title: '复选框',
    category: '表单与选择',
    description: '用于多个独立选项，可表达未选、已选和混合状态。',
    composition: ['Checkbox', '└─ indicator'],
    states: ['未选', '已选', '混合', '焦点', '禁用', '无效'],
  },
  {
    id: 'collapsible',
    name: 'Collapsible',
    title: '折叠容器',
    category: '基础与内容',
    description: '控制单一区域显隐，适合高级设置或次级内容。',
    composition: ['Collapsible', '├─ CollapsibleTrigger', '└─ CollapsibleContent'],
    states: ['收起', '展开', '禁用'],
  },
  {
    id: 'combobox',
    name: 'Combobox',
    title: '组合框',
    category: '表单与选择',
    description: '把输入、筛选与选择合并，适合选项较多或需要搜索的场景。',
    composition: ['Combobox', '├─ ComboboxInput', '├─ ComboboxTrigger', '└─ ComboboxContent', '   └─ ComboboxList', '      ├─ ComboboxItem', '      └─ ComboboxEmpty'],
    states: ['空值', '输入中', '展开', '已选择', '无结果', '禁用', '无效'],
  },
  {
    id: 'command',
    name: 'Command',
    title: '命令面板',
    category: '覆盖层与菜单',
    description: '用于快速搜索并执行命令、跳转或选择，重点是键盘效率和结果反馈。',
    composition: ['Command', '├─ CommandInput', '└─ CommandList', '   ├─ CommandGroup', '   ├─ CommandItem', '   ├─ CommandSeparator', '   └─ CommandEmpty'],
    states: ['默认列表', '搜索中', '匹配结果', '空结果', '禁用项', '选中项'],
  },
  {
    id: 'context-menu',
    name: 'Context Menu',
    title: '上下文菜单',
    category: '覆盖层与菜单',
    description: '针对当前对象提供局部操作，通常由右键或长按触发。',
    composition: ['ContextMenu', '├─ ContextMenuTrigger', '└─ ContextMenuContent', '   ├─ ContextMenuItem', '   ├─ ContextMenuCheckboxItem', '   ├─ ContextMenuRadioItem', '   ├─ ContextMenuSub', '   └─ ContextMenuSeparator'],
    states: ['关闭', '打开', '普通项', '禁用项', '选中项', '破坏性项', '子菜单'],
  },
  {
    id: 'dialog',
    name: 'Dialog',
    title: '对话框',
    category: '覆盖层与菜单',
    description: '把需要用户集中处理的内容置于模态层，并保持明确的进入和退出路径。',
    composition: ['Dialog', '├─ DialogTrigger', '└─ DialogContent', '   ├─ DialogHeader', '   │  ├─ DialogTitle', '   │  └─ DialogDescription', '   └─ DialogFooter / DialogClose'],
    states: ['关闭', '打开', '可关闭', '不可误关闭'],
  },
  {
    id: 'direction',
    name: 'Direction',
    title: '方向上下文',
    category: '导航与结构',
    description: '为组件树提供 LTR / RTL 方向上下文，用于验证逻辑方向布局。',
    composition: ['DirectionProvider', '└─ component tree'],
    states: ['LTR', 'RTL'],
  },
  {
    id: 'drawer',
    name: 'Drawer',
    title: '抽屉',
    category: '覆盖层与菜单',
    description: '从视窗边缘进入的临时任务层，适合移动端操作与次级任务。',
    composition: ['Drawer', '├─ DrawerTrigger', '└─ DrawerContent', '   ├─ DrawerHeader', '   ├─ DrawerBody', '   └─ DrawerFooter'],
    states: ['关闭', '打开', '顶部 / 右侧 / 底部 / 左侧'],
  },
  {
    id: 'dropdown-menu',
    name: 'Dropdown Menu',
    title: '下拉菜单',
    category: '覆盖层与菜单',
    description: '从按钮或其他触发器展开一组动作和选择。',
    composition: ['DropdownMenu', '├─ DropdownMenuTrigger', '└─ DropdownMenuContent', '   ├─ DropdownMenuItem', '   ├─ DropdownMenuCheckboxItem', '   ├─ DropdownMenuRadioItem', '   ├─ DropdownMenuSub', '   └─ DropdownMenuSeparator'],
    states: ['关闭', '打开', '普通项', '禁用项', '复选项', '单选项', '破坏性项', '子菜单'],
  },
  {
    id: 'empty',
    name: 'Empty',
    title: '空状态',
    category: '数据与反馈',
    description: '当没有数据、没有结果或还未创建内容时，解释当前状态并给出下一步。',
    composition: ['Empty', '├─ EmptyHeader', '│  ├─ EmptyMedia', '│  ├─ EmptyTitle', '│  └─ EmptyDescription', '└─ EmptyContent'],
    states: ['无数据', '无搜索结果', '可创建', '只读'],
  },
  {
    id: 'field',
    name: 'Field',
    title: '字段',
    category: '表单与选择',
    description: '统一表单字段的标签、描述、控件和错误信息关系。',
    composition: ['Field', '├─ FieldLabel', '├─ control', '├─ FieldDescription', '└─ FieldError'],
    states: ['纵向', '横向', '响应式', '默认', '禁用', '无效', '带描述', '带错误'],
  },
  {
    id: 'hover-card',
    name: 'Hover Card',
    title: '悬停卡片',
    category: '覆盖层与菜单',
    description: '在 hover / focus 时补充对象信息，不承载必须完成的任务。',
    composition: ['HoverCard', '├─ HoverCardTrigger', '└─ HoverCardContent'],
    states: ['关闭', '悬停打开', '键盘焦点打开'],
  },
  {
    id: 'input',
    name: 'Input',
    title: '输入框',
    category: '表单与选择',
    description: '单行文本输入控件，状态需要明确但不能抢夺正文注意力。',
    composition: ['Input'],
    states: ['空值', '有值', '悬停', '焦点', '禁用', '无效'],
  },
  {
    id: 'input-group',
    name: 'Input Group',
    title: '输入组合',
    category: '表单与选择',
    description: '把输入框与图标、前后缀、按钮或说明组合成一个连续控制面。',
    composition: ['InputGroup', '├─ InputGroupAddon', '├─ InputGroupInput', '├─ InputGroupTextarea', '└─ InputGroupButton'],
    states: ['前缀', '后缀', '带按钮', '焦点', '禁用', '无效'],
  },
  {
    id: 'input-otp',
    name: 'Input OTP',
    title: '验证码输入',
    category: '表单与选择',
    description: '按固定槽位输入一次性验证码，并明确当前输入位置。',
    composition: ['InputOTP', '└─ InputOTPGroup', '   ├─ InputOTPSlot', '   └─ InputOTPSeparator'],
    states: ['空槽', '已输入', '当前槽位', '完成', '禁用'],
  },
  {
    id: 'item',
    name: 'Item',
    title: '条目',
    category: '基础与内容',
    description: '构建列表、设置项或紧凑卡片的通用内容条目。',
    composition: ['Item', '├─ ItemMedia', '├─ ItemContent', '│  ├─ ItemTitle', '│  └─ ItemDescription', '└─ ItemActions'],
    states: ['默认', '轮廓', '弱化', '链接', '焦点', 'XS / SM / MD'],
  },
  {
    id: 'kbd',
    name: 'Kbd',
    title: '键盘按键',
    category: '基础与内容',
    description: '以紧凑视觉形式标记键盘快捷键或键位组合。',
    composition: ['KbdGroup', '├─ Kbd', '└─ Kbd'],
    states: ['单键', '组合键'],
  },
  {
    id: 'label',
    name: 'Label',
    title: '标签',
    category: '表单与选择',
    description: '为输入和选择控件提供可点击、可访问的名称。',
    composition: ['Label', '└─ text'],
    states: ['默认', '关联控件', '禁用关联'],
  },
  {
    id: 'marker',
    name: 'Marker',
    title: '分段标记',
    category: '消息与会话',
    description: '在内容流中标记时间、阶段或分界点。',
    composition: ['Marker', '├─ MarkerIcon', '└─ MarkerContent'],
    states: ['默认', '分隔线', '底边框'],
  },
  {
    id: 'message',
    name: 'Message',
    title: '消息行',
    category: '消息与会话',
    description: '组织一条完整消息的发送方、内容、头尾信息和对齐关系。',
    composition: ['MessageGroup', '└─ Message', '   ├─ MessageAvatar', '   └─ MessageContent', '      ├─ MessageHeader', '      ├─ Bubble', '      └─ MessageFooter'],
    states: ['接收方', '发送方', '带头像', '带头部', '带尾部'],
  },
  {
    id: 'message-scroller',
    name: 'Message Scroller',
    title: '消息滚动器',
    category: '消息与会话',
    description: '为持续追加的消息流保持滚动位置、锚点与回到底部操作。',
    composition: ['MessageScrollerProvider', '└─ MessageScroller', '   ├─ MessageScrollerViewport', '   │  └─ MessageScrollerContent', '   │     └─ MessageScrollerItem', '   └─ MessageScrollerButton'],
    states: ['位于底部', '离开底部', '自动滚动', '滚动按钮显示 / 隐藏'],
  },
  {
    id: 'native-select',
    name: 'Native Select',
    title: '原生选择框',
    category: '表单与选择',
    description: '保留浏览器原生 select 行为，同时统一视觉表面。',
    composition: ['NativeSelect', '├─ option', '└─ NativeSelectIcon'],
    states: ['占位', '已选择', '焦点', '禁用', '无效'],
  },
  {
    id: 'pagination',
    name: 'Pagination',
    title: '分页',
    category: '导航与结构',
    description: '在离散页之间移动并持续表达当前位置。',
    composition: ['Pagination', '└─ PaginationContent', '   ├─ PaginationPrevious', '   ├─ PaginationItem / PaginationLink', '   ├─ PaginationEllipsis', '   └─ PaginationNext'],
    states: ['普通页', '当前页', '上一页禁用', '下一页禁用', '省略'],
  },
  {
    id: 'popover',
    name: 'Popover',
    title: '浮层',
    category: '覆盖层与菜单',
    description: '在触发对象附近显示补充内容或轻量操作，并保持空间关联。',
    composition: ['Popover', '├─ PopoverTrigger', '└─ PopoverContent', '   ├─ PopoverHeader', '   ├─ PopoverTitle', '   └─ PopoverDescription'],
    states: ['关闭', '打开', '不同方位'],
  },
  {
    id: 'progress',
    name: 'Progress',
    title: '进度',
    category: '数据与反馈',
    description: '表达任务推进程度；未知进度时应使用不确定状态而非伪造百分比。',
    composition: ['Progress', '├─ ProgressLabel', '├─ ProgressTrack / ProgressIndicator', '└─ ProgressValue'],
    states: ['0%', '进行中', '接近完成', '完成', '不确定'],
  },
  {
    id: 'questionnaire',
    name: 'Questionnaire',
    title: '问卷',
    category: '表单与选择',
    description: '组织多步骤问题、选择、输入和前后导航，持续保留进度上下文。',
    composition: ['Questionnaire', '├─ QuestionnaireProgress', '├─ QuestionnaireItem', '│  ├─ QuestionnaireTitle', '│  ├─ QuestionnaireDescription', '│  └─ QuestionnaireChoices / QuestionnaireInput', '└─ QuestionnaireActions'],
    states: ['单选', '多选', '文本输入', '已选择', '禁用', '无效', '上一步 / 下一步 / 提交'],
  },
  {
    id: 'radio-group',
    name: 'Radio Group',
    title: '单选组',
    category: '表单与选择',
    description: '从互斥选项中选择一个值，并明确当前选择。',
    composition: ['RadioGroup', '└─ RadioGroupItem'],
    states: ['未选', '已选', '焦点', '禁用', '无效'],
  },
  {
    id: 'resizable',
    name: 'Resizable',
    title: '可调整面板',
    category: '导航与结构',
    description: '允许用户直接拖动分隔线调整相邻区域尺寸。',
    composition: ['ResizablePanelGroup', '├─ ResizablePanel', '├─ ResizableHandle', '└─ ResizablePanel'],
    states: ['水平', '垂直', '静止', '拖动'],
  },
  {
    id: 'scroll-area',
    name: 'Scroll Area',
    title: '滚动区域',
    category: '导航与结构',
    description: '限制内容视窗并提供一致的滚动容器行为。',
    composition: ['ScrollArea', '└─ scrollable content'],
    states: ['顶部', '中间', '底部', '可滚动'],
  },
  {
    id: 'select',
    name: 'Select',
    title: '选择框',
    category: '表单与选择',
    description: '从预定义选项中选择一个值，适合无需自由输入的集合。',
    composition: ['Select', '├─ SelectTrigger / SelectValue', '└─ SelectContent', '   └─ SelectList', '      ├─ SelectItem', '      ├─ SelectSeparator', '      └─ SelectEmpty'],
    states: ['空值', '已选择', '展开', '禁用', '无效', '空列表'],
  },
  {
    id: 'separator',
    name: 'Separator',
    title: '分隔线',
    category: '基础与内容',
    description: '在必要时强化已经存在的分组关系，不替代正确的空间节奏。',
    composition: ['Separator'],
    states: ['水平', '垂直'],
  },
  {
    id: 'sheet',
    name: 'Sheet',
    title: '侧边面板',
    category: '覆盖层与菜单',
    description: '从边缘覆盖进入的任务面板，常用于辅助编辑、筛选或导航。',
    composition: ['Sheet', '├─ SheetTrigger', '└─ SheetContent', '   ├─ SheetHeader', '   ├─ SheetTitle / SheetDescription', '   └─ SheetFooter'],
    states: ['关闭', '打开', '左侧', '右侧', '顶部', '底部'],
  },
  {
    id: 'sidebar',
    name: 'Sidebar',
    title: '侧边栏',
    category: '导航与结构',
    description: '承载稳定的全局或局部导航，在空间不足时切换为紧凑或移动端呈现。',
    composition: ['SidebarProvider', '├─ Sidebar', '│  ├─ SidebarHeader', '│  ├─ SidebarContent', '│  │  └─ SidebarMenu', '│  └─ SidebarFooter', '└─ SidebarTrigger'],
    states: ['展开', '折叠', '移动端', '当前项', '普通项', '禁用项'],
  },
  {
    id: 'skeleton',
    name: 'Skeleton',
    title: '骨架屏',
    category: '数据与反馈',
    description: '在结构已知但内容仍在等待时提供占位，避免布局跳动。',
    composition: ['Skeleton'],
    states: ['文字', '头像', '卡片', '组合占位'],
  },
  {
    id: 'slider',
    name: 'Slider',
    title: '滑块',
    category: '表单与选择',
    description: '通过直接拖动在连续或离散范围内选择数值。',
    composition: ['Slider'],
    states: ['最小值', '中间值', '最大值', '范围', '焦点', '禁用'],
  },
  {
    id: 'spinner',
    name: 'Spinner',
    title: '加载指示器',
    category: '数据与反馈',
    description: '表示短时等待或局部处理中；长期任务应优先展示进度。',
    composition: ['Spinner'],
    states: ['小', '默认', '大', '与按钮组合'],
  },
  {
    id: 'switch',
    name: 'Switch',
    title: '开关',
    category: '表单与选择',
    description: '在两个立即生效的状态之间切换，开与关都必须可辨。',
    composition: ['Switch', '└─ thumb'],
    states: ['关闭', '开启', '悬停', '按下', '焦点', '禁用'],
  },
  {
    id: 'table',
    name: 'Table',
    title: '表格',
    category: '数据与反馈',
    description: '以行列关系呈现结构化数据，保持标题、数值和扫描路径清晰。',
    composition: ['Table', '├─ TableHeader', '│  └─ TableRow / TableHead', '├─ TableBody', '│  └─ TableRow / TableCell', '└─ TableFooter / TableCaption'],
    states: ['表头', '普通行', '悬停行', '选中行', '空数据'],
  },
  {
    id: 'tabs',
    name: 'Tabs',
    title: '标签页',
    category: '导航与结构',
    description: '在同一上下文内切换同级内容，不改变用户所在的主要位置。',
    composition: ['Tabs', '├─ TabsList', '│  └─ TabsTrigger', '└─ TabsContent'],
    states: ['未选', '已选', '悬停', '按下', '焦点', '禁用', '默认样式', '线型'],
  },
  {
    id: 'textarea',
    name: 'Textarea',
    title: '多行输入',
    category: '表单与选择',
    description: '承载多行自由文本输入，并保持输入、错误与辅助说明的关系。',
    composition: ['Textarea'],
    states: ['空值', '有值', '焦点', '禁用', '无效'],
  },
  {
    id: 'toggle',
    name: 'Toggle',
    title: '切换按钮',
    category: '表单与选择',
    description: '以按钮外观表达可保持的开 / 关选择状态。',
    composition: ['Toggle'],
    states: ['未选', '已选', '悬停', '按下', '焦点', '禁用', '不同尺寸'],
  },
  {
    id: 'toggle-group',
    name: 'Toggle Group',
    title: '切换按钮组',
    category: '表单与选择',
    description: '组织一组相关 Toggle，可用于单选或多选模式。',
    composition: ['ToggleGroup', '└─ ToggleGroupItem'],
    states: ['单选', '多选', '未选', '已选', '禁用'],
  },
  {
    id: 'tooltip',
    name: 'Tooltip',
    title: '工具提示',
    category: '覆盖层与菜单',
    description: '在 hover / focus 时解释图标或陌生操作，不承载关键任务。',
    composition: ['TooltipProvider', '└─ Tooltip', '   ├─ TooltipTrigger', '   └─ TooltipContent'],
    states: ['关闭', '悬停打开', '键盘打开', '上 / 右 / 下 / 左'],
  },
]

export const componentIds = componentDocs.map((item) => item.id)
